# Generated by Django 4.2 on 2024-08-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_registration',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
    ]
