# Generated by Django 4.2 on 2024-09-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_priority'),
        ('users', '0004_alter_user_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.course', verbose_name='Course'),
        ),
    ]
