# Generated by Django 4.2 on 2024-09-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_priority'),
        ('users', '0005_user_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.course', verbose_name='Купленные курсы'),
        ),
    ]
