# Generated by Django 4.2 on 2024-09-14 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_balance_user_user_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='balance',
        ),
    ]
