# Generated by Django 4.2 on 2024-09-15 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_balance_user_balance_owner_user_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cash',
        ),
        migrations.AlterField(
            model_name='balance',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
