# Generated by Django 4.2 on 2024-09-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='priority',
            field=models.PositiveIntegerField(verbose_name='Порядок'),
        ),
    ]
