# Generated by Django 4.2 on 2024-09-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='final_date',
            field=models.DateTimeField(null=True, verbose_name='День сдачи'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.PositiveIntegerField(verbose_name='Срок сдачи'),
        ),
    ]
